name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Code
    - name: Build
      run: dotnet build --no-restore
      working-directory: Code
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: Code
    - name: Simply Web Deploy
    # You may pin to the exact commit or the version.
    # uses: RasmusBuchholdt/simply-web-deploy@ba10f99c58f47b31cd8979163a4d40894193019e
      uses: RasmusBuchholdt/simply-web-deploy@2.0.0
      with:
        # IIS website name
        website-name: ${{ secrets.MSDEPLOYSITE }}
        # IIS server computer name
        server-computer-name: ${{ secrets.PUBLISHURL }}
        # IIS server username
        server-username: ${{ secrets.USERNAME }}
        # IIS server password
        server-password: ${{ secrets.PASSWORD }}
        # The source directory for payload
        source-path: \Code\WebAnalyser\bin\Release\net6.0
        # optional, default is \publish\
        # Delete files on the destination computer that do not exist on the source computer
