name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Code
    - name: Build
      run: dotnet build --no-restore
      working-directory: Code
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: Code
    - name: Publish
      run: dotnet publish WebAnalyser/WebAnalyser.csproj --configuration Release --output ./publish --runtime win-x86 --self-contained true -p:PublishTrimmed=false -p:PublishSingleFile=false
      working-directory: Code
    - name: Deploy to Simply
      uses: RasmusBuchholdt/simply-web-deploy@2.0.0
      with:
        website-name: ${{ secrets.WEBSITE_NAME }}
        server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
        server-username: ${{ secrets.SERVER_USERNAME }}
        server-password: ${{ secrets.SERVER_PASSWORD }}

